language: cpp

compiler:
  - gcc

sudo: required
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install protobuf gtest benchmark ms-gsl
  - export VCPKG_ROOT=$(pwd)
  - cd ..
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make -j2 && ctest -j2
  - ./bin/fuzzy_search_benchmark

notifications:
  email: false
