language: cpp

compiler:
  - gcc

sudo: required
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.13.2-bionic'
    packages:
      - g++-7
      - qt513base
      - qt513tools

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  # - sudo apt-get install qtbase5-dev qtdeclarative5-dev
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install gtest benchmark ms-gsl
  - export VCPKG_ROOT=$(pwd)
  - export CMAKE_PREFIX_PATH=/opt/qt513/
  - cd ..
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make -j2 && ctest -j2
  - ./bin/fuzzy_search_benchmark
  - ./bin/history_model_benchmark

notifications:
  email: false
